# edit username to reflect your own
model:
  model_path: "/home/hice1/username/diffcsp_con/pretrained_checkpoints"
  save_path: "/home/hice1/username/diffcsp_con/sample_output"
  formula: "B2O3"
  num_evals: 100
  batch_size: 500
  step_lr: 1e-5
  lattice:
    lengths: [5.43, 5.43, 5.43]  # Update with appropriate values
    angles: [90, 90, 90]         # Update with appropriate values
